# Nerd Fonts: per-user install (no admin), like Omarchy's Install > Style > Font.

# Omarchy's font menu (bin/omarchy-install-font list) -> nerd-fonts release zip names.
$NerdFonts = [ordered]@{
    'JetBrainsMono'         = 'JetBrainsMono Nerd Font'
    'CascadiaMono'          = 'CaskaydiaMono Nerd Font'
    'Meslo'                 = 'MesloLGM Nerd Font'
    'FiraCode'              = 'FiraCode Nerd Font'
    'VictorMono'            = 'VictorMono Nerd Font'
    'BitstreamVeraSansMono' = 'BitstromWera Nerd Font'
    'Iosevka'               = 'Iosevka Nerd Font'
}

function Install-FontFile([string]$file) {
    Initialize-Native
    $dir = Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Fonts'
    New-Item -ItemType Directory -Force $dir | Out-Null
    $dest = Join-Path $dir ([IO.Path]::GetFileName($file))
    Save-File $dest
    Copy-Item -Force $file $dest
    Add-Type -AssemblyName PresentationCore
    $face = try { ([System.Windows.Media.GlyphTypeface]::new([Uri]$dest)).Win32FamilyNames['en-US'] } catch { [IO.Path]::GetFileNameWithoutExtension($dest) }
    $style = try { ([System.Windows.Media.GlyphTypeface]::new([Uri]$dest)).Win32FaceNames['en-US'] } catch { '' }
    $name = "$face $style (TrueType)".Replace('  ', ' ')
    $key = 'HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Fonts'
    if (-not (Test-Path $key)) { New-Item -Force $key | Out-Null }
    Save-Reg $key $name
    Set-ItemProperty $key -Name $name -Value $dest
    [void][Winarchy.Native]::AddFontResource($dest)
}

# fonts.json for Style > Font: installed monospace families (per-user fonts included),
# Nerd Fonts first, weight/style variants folded into their family.
function Update-FontList {
    Add-Type -AssemblyName System.Drawing, System.Windows.Forms
    $weights = '\b(Thin|ExtraLight|UltraLight|Light|SemiLight|Regular|Medium|SemiBold|DemiBold|Bold|ExtraBold|UltraBold|Black|Heavy|Italic|Oblique|Condensed|Expanded|Retina|Text)\b'
    $fonts = [Collections.Generic.List[object]]::new()
    $seen = @{}
    foreach ($fam in ([System.Drawing.Text.InstalledFontCollection]::new()).Families) {
        $name = $fam.Name
        if ($name.StartsWith('@') -or $name -match $weights -or $name -match 'Propo|NFP$' -or $seen[$name]) { continue }
        try {
            $f = [System.Drawing.Font]::new($fam, 12)
            $narrow = [System.Windows.Forms.TextRenderer]::MeasureText('iiiiiiiiii', $f).Width
            $wide = [System.Windows.Forms.TextRenderer]::MeasureText('WWWWWWWWWW', $f).Width
            $f.Dispose()
            if ([Math]::Abs($narrow - $wide) -gt 2) { continue }   # proportional
        } catch { continue }
        $seen[$name] = $true
        $fonts.Add([ordered]@{ name = $name; nerd = [bool]($name -match 'Nerd Font|\bNF\b|NFM$') })
    }
    $sorted = @($fonts | Sort-Object @{ e = { -not $_.nerd } }, @{ e = { $_.name } })
    Write-Json (Join-Path $Pack 'fonts.json') ([ordered]@{ generated = (Get-Date).ToString('s'); fonts = $sorted })
    $sorted
}

# Omarchy's omarchy-font-set: terminal, bar + menus, launcher, popups follow one font.
function Invoke-FontSet([string]$family) {
    if (-not $family) { throw 'usage: winarchy font <family>   (winarchy font list)' }
    $s = Read-State
    $s.font = $family
    Save-State $s
    Write-FontCss $family
    $p = Get-Paths
    if ($p.wtSettings -and (Test-Path $p.wtSettings)) {
        $wt = Read-Json $p.wtSettings
        Save-JsonProperty $p.wtSettings 'profiles.defaults.font.face'
        $d = Get-TerminalDefaults $wt
        if (-not $d.font) { $d | Add-Member -Force -NotePropertyName font -NotePropertyValue ([pscustomobject]@{}) }
        $d.font | Add-Member -Force -NotePropertyName face -NotePropertyValue $family
        foreach ($prof in @($wt.profiles.list | Where-Object { $_.name -in 'Omarchy Screensaver' })) {
            if ($prof.font) { $prof.font | Add-Member -Force -NotePropertyName face -NotePropertyValue $family }
        }
        Write-Json $p.wtSettings $wt
        Log "font $family -> Windows Terminal"
    }
    try { Set-FlowTheme (Read-Colors $s.theme); Log "font $family -> Flow Launcher" } catch { Log "font -> Flow FAILED: $($_.Exception.Message)" }
    Write-Status $s -BumpTheme
    Log "font $family -> bar + menus"
}

function Write-FontCss([string]$family) {
    if (-not $family) { $family = Get-FontFamily }
    $safe = $family -replace "['\\;{}]", ''
    # Text size (Display panel): the bar, menu and panels zoom by --text-scale, the way
    # Quattro's shell scales its fonts and spacing from one base size (12px = 1).
    $px = Get-TextSize
    $scale = [Math]::Round($px / 12, 4).ToString([Globalization.CultureInfo]::InvariantCulture)
    Write-PackFile 'font.css' "/* Generated by winarchy font-set / text-size. */`n:root { --font: '$safe'; --text-size: ${px}px; --text-scale: $scale; }`n"
}

# Omarchy's omarchy-display-text-size: one size (px, 12 = default) for the shell and the
# terminals. Quattro's panel snaps to these stops; the CLI takes any whole size in range.
$TextSizeStops = @(9, 10, 11, 12, 14, 16, 20)
$TextSizeMin = 9
$TextSizeMax = 20
$AlacrittyConfig = Join-Path $env:APPDATA 'alacritty\alacritty.toml'

function Get-TextSize {
    $px = 12
    try { $v = (Get-Config).textSize; if ($null -ne $v) { $px = [int]$v } } catch {}
    [Math]::Max($TextSizeMin, [Math]::Min($TextSizeMax, $px))
}

# Terminal points for a shell size in px: omarchy-display-text-size's pt = px * 9 / 12, so
# the default 12px keeps the terminals at 9pt... except Windows Terminal ships at 12pt, not
# Alacritty's 9: its size is scaled from its own default instead (12px = 12pt).
function ConvertTo-TerminalPoints([int]$px, [double]$base = 9) {
    [Math]::Round($px * $base / 12, 1)
}

function Invoke-TextSize([string]$size) {
    if (-not $size) { return "text size: $(Get-TextSize)px   (winarchy text-size <$TextSizeMin-$TextSizeMax> | reset)" }
    $px = if ($size -eq 'reset') { 12 } else {
        $n = 0
        if (-not [int]::TryParse($size.TrimEnd('px'), [ref]$n) -or $n -lt $TextSizeMin -or $n -gt $TextSizeMax) {
            throw "text size must be a whole number of px from $TextSizeMin to $TextSizeMax (or reset)"
        }
        $n
    }
    $oldBar = Get-BarHeight (Get-Config)
    Set-ConfigValue 'textSize' $px
    Write-FontCss
    Set-TerminalFontSize $px
    $s = Read-State
    Write-Status $s -BumpTheme
    Log "text size ${px}px -> bar, menus, panels, terminals"
    # A bigger size needs a taller bar: that is GlazeWM's top gap and the bar window, so
    # re-apply (which restarts the bar). Sizes at or under 12px keep the bar as it is.
    if ((Get-BarHeight (Get-Config)) -ne $oldBar) { Invoke-Apply }
}

# Windows Terminal (settings.json, reloads by itself), and Alacritty when it has a config.
function Set-TerminalFontSize([int]$px) {
    $p = Get-Paths
    if ($p.wtSettings -and (Test-Path $p.wtSettings)) {
        $wt = Read-Json $p.wtSettings
        Save-JsonProperty $p.wtSettings 'profiles.defaults.font.size'
        $d = Get-TerminalDefaults $wt
        if (-not $d.font) { $d | Add-Member -Force -NotePropertyName font -NotePropertyValue ([pscustomobject]@{}) }
        $d.font | Add-Member -Force -NotePropertyName size -NotePropertyValue (ConvertTo-TerminalPoints $px 12)
        Write-Json $p.wtSettings $wt
        Log "text size ${px}px -> Windows Terminal $(ConvertTo-TerminalPoints $px 12)pt"
    }
    $alacritty = $AlacrittyConfig
    if (Test-Path $alacritty) {
        $pt = (ConvertTo-TerminalPoints $px).ToString([Globalization.CultureInfo]::InvariantCulture)
        $text = Get-Content -Raw $alacritty
        $next = if ($text -match '(?m)^\s*size\s*=') { $text -replace '(?m)^(\s*size\s*=\s*)[0-9.]+', "`${1}$pt" }
                elseif ($text -match '(?m)^\[font\]\s*$') { $text -replace '(?m)^\[font\]\s*$', "[font]`nsize = $pt" }
                else { $text.TrimEnd() + "`n`n[font]`nsize = $pt`n" }
        if ($next -ne $text) { Save-File $alacritty; Write-Utf8 $alacritty $next; Log "text size ${px}px -> Alacritty ${pt}pt" }
    }
}

# Downloads <Name>.zip from the latest nerd-fonts release and installs its standard
# "<Name>NerdFont-*.ttf" files (not the Mono/Propo variants) for this user.
function Install-NerdFont([string]$name) {
    if (-not $NerdFonts.Contains($name)) { throw "unknown font '$name' (choose: $($NerdFonts.Keys -join ', '))" }
    $tmp = Join-Path $env:TEMP "omarchy-font-$name"
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force $tmp | Out-Null
    $base = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$name"
    $x = Join-Path $tmp 'x'
    New-Item -ItemType Directory -Force $x | Out-Null
    Log "downloading $name Nerd Font"
    # The .tar.xz holds the same fonts at a fraction of the size (JetBrainsMono: 7 MB
    # against 128 MB), and Windows' own tar reads xz. The zip stays as a fallback.
    try {
        Invoke-WebRequest "$base.tar.xz" -OutFile "$tmp\$name.tar.xz" -TimeoutSec 600
        tar -xf "$tmp\$name.tar.xz" -C $x
        if ($LASTEXITCODE) { throw "tar exit $LASTEXITCODE" }
    } catch {
        Log "$name.tar.xz failed ($($_.Exception.Message)): downloading the zip"
        Invoke-WebRequest "$base.zip" -OutFile "$tmp\$name.zip" -TimeoutSec 600
        Expand-Archive "$tmp\$name.zip" $x -Force
    }
    $files = Get-ChildItem (Join-Path $tmp 'x') -Recurse -Include *.ttf, *.otf |
        Where-Object { $_.Name -match 'NerdFont-' -and $_.Name -notmatch 'NerdFont(Mono|Propo)-' }
    if (-not $files) { $files = Get-ChildItem (Join-Path $tmp 'x') -Recurse -Include *.ttf, *.otf }
    foreach ($f in $files) { Install-FontFile $f.FullName }
    $r = [UIntPtr]::Zero   # WM_FONTCHANGE: running apps see the new font
    [void][Winarchy.Native]::SendMessageTimeout([IntPtr]0xffff, 0x1D, [UIntPtr]::Zero, $null, 2, 1000, [ref]$r)
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    Log "installed $($files.Count) $name font file(s)"
    $NerdFonts[$name]
}
