# Nerd Fonts: per-user install (no admin), like Omarchy's Install > Style > Font.

# Omarchy's font menu (bin/omarchy-install-font list) -> nerd-fonts release zip names.
$NerdFonts = [ordered]@{
    'JetBrainsMono'         = 'JetBrainsMono Nerd Font'
    'CascadiaMono'          = 'CaskaydiaMono Nerd Font'
    'Meslo'                 = 'MesloLGM Nerd Font'
    'FiraCode'              = 'FiraCode Nerd Font'
    'VictorMono'            = 'VictorMono Nerd Font'
    'BitstreamVeraSansMono' = 'BitstromWera Nerd Font'
    'Iosevka'               = 'Iosevka Nerd Font'
}

function Install-FontFile([string]$file) {
    Initialize-Native
    $dir = Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Fonts'
    New-Item -ItemType Directory -Force $dir | Out-Null
    $dest = Join-Path $dir ([IO.Path]::GetFileName($file))
    Copy-Item -Force $file $dest
    Add-Type -AssemblyName PresentationCore
    $face = try { ([System.Windows.Media.GlyphTypeface]::new([Uri]$dest)).Win32FamilyNames['en-US'] } catch { [IO.Path]::GetFileNameWithoutExtension($dest) }
    $style = try { ([System.Windows.Media.GlyphTypeface]::new([Uri]$dest)).Win32FaceNames['en-US'] } catch { '' }
    $name = "$face $style (TrueType)".Replace('  ', ' ')
    $key = 'HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Fonts'
    if (-not (Test-Path $key)) { New-Item -Force $key | Out-Null }
    Set-ItemProperty $key -Name $name -Value $dest
    [void][OmarchyWin.Native]::AddFontResource($dest)
}

# fonts.json for Style > Font: installed monospace families (per-user fonts included),
# Nerd Fonts first, weight/style variants folded into their family.
function Update-FontList {
    Add-Type -AssemblyName System.Drawing, System.Windows.Forms
    $weights = '\b(Thin|ExtraLight|UltraLight|Light|SemiLight|Regular|Medium|SemiBold|DemiBold|Bold|ExtraBold|UltraBold|Black|Heavy|Italic|Oblique|Condensed|Expanded|Retina|Text)\b'
    $fonts = [Collections.Generic.List[object]]::new()
    $seen = @{}
    foreach ($fam in ([System.Drawing.Text.InstalledFontCollection]::new()).Families) {
        $name = $fam.Name
        if ($name.StartsWith('@') -or $name -match $weights -or $name -match 'Propo|NFP$' -or $seen[$name]) { continue }
        try {
            $f = [System.Drawing.Font]::new($fam, 12)
            $narrow = [System.Windows.Forms.TextRenderer]::MeasureText('iiiiiiiiii', $f).Width
            $wide = [System.Windows.Forms.TextRenderer]::MeasureText('WWWWWWWWWW', $f).Width
            $f.Dispose()
            if ([Math]::Abs($narrow - $wide) -gt 2) { continue }   # proportional
        } catch { continue }
        $seen[$name] = $true
        $fonts.Add([ordered]@{ name = $name; nerd = [bool]($name -match 'Nerd Font|\bNF\b|NFM$') })
    }
    $sorted = @($fonts | Sort-Object @{ e = { -not $_.nerd } }, @{ e = { $_.name } })
    Write-Json (Join-Path $Pack 'fonts.json') ([ordered]@{ generated = (Get-Date).ToString('s'); fonts = $sorted })
    $sorted
}

# Omarchy's omarchy-font-set: terminal, bar + menus, launcher, popups follow one font.
function Invoke-FontSet([string]$family) {
    if (-not $family) { throw 'usage: omarchy-win font <family>   (omarchy-win font list)' }
    $s = Read-State
    $s.font = $family
    Save-State $s
    Write-FontCss $family
    $p = Get-Paths
    if ($p.wtSettings -and (Test-Path $p.wtSettings)) {
        $wt = Read-Json $p.wtSettings
        Save-JsonProperty $p.wtSettings 'profiles.defaults.font.face'
        $d = Get-TerminalDefaults $wt
        if (-not $d.font) { $d | Add-Member -Force -NotePropertyName font -NotePropertyValue ([pscustomobject]@{}) }
        $d.font | Add-Member -Force -NotePropertyName face -NotePropertyValue $family
        foreach ($prof in @($wt.profiles.list | Where-Object { $_.name -in 'Omarchy Screensaver' })) {
            if ($prof.font) { $prof.font | Add-Member -Force -NotePropertyName face -NotePropertyValue $family }
        }
        Write-Json $p.wtSettings $wt
        Log "font $family -> Windows Terminal"
    }
    try { Set-FlowTheme (Read-Colors $s.theme); Log "font $family -> Flow Launcher" } catch { Log "font -> Flow FAILED: $($_.Exception.Message)" }
    Write-Status $s -BumpTheme
    Log "font $family -> bar + menus"
}

function Write-FontCss([string]$family) {
    if (-not $family) { $family = Get-FontFamily }
    $safe = $family -replace "['\\;{}]", ''
    Write-Utf8 (Join-Path $Pack 'font.css') "/* Generated by omarchy-win font-set. */`n:root { --font: '$safe'; }`n"
}

# Downloads <Name>.zip from the latest nerd-fonts release and installs its standard
# "<Name>NerdFont-*.ttf" files (not the Mono/Propo variants) for this user.
function Install-NerdFont([string]$name) {
    if (-not $NerdFonts.Contains($name)) { throw "unknown font '$name' (choose: $($NerdFonts.Keys -join ', '))" }
    $tmp = Join-Path $env:TEMP "omarchy-font-$name"
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force $tmp | Out-Null
    $zip = Join-Path $tmp "$name.zip"
    Log "downloading $name Nerd Font"
    Invoke-WebRequest "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$name.zip" -OutFile $zip -TimeoutSec 600
    Expand-Archive $zip (Join-Path $tmp 'x') -Force
    $files = Get-ChildItem (Join-Path $tmp 'x') -Recurse -Include *.ttf, *.otf |
        Where-Object { $_.Name -match 'NerdFont-' -and $_.Name -notmatch 'NerdFont(Mono|Propo)-' }
    if (-not $files) { $files = Get-ChildItem (Join-Path $tmp 'x') -Recurse -Include *.ttf, *.otf }
    foreach ($f in $files) { Install-FontFile $f.FullName }
    $r = [UIntPtr]::Zero   # WM_FONTCHANGE: running apps see the new font
    [void][OmarchyWin.Native]::SendMessageTimeout([IntPtr]0xffff, 0x1D, [UIntPtr]::Zero, $null, 2, 1000, [ref]$r)
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    Log "installed $($files.Count) $name font file(s)"
    $NerdFonts[$name]
}
