<!--
  Flow Launcher theme in the style of Omarchy's menu (generated by omarchy.ps1 theme-set).
  {{ key }} placeholders come from the Omarchy theme's colors.toml.
-->
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:system="clr-namespace:System;assembly=mscorlib">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/Themes/Base.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <CornerRadius x:Key="ItemRadius">0</CornerRadius>
    <Thickness x:Key="ItemMargin">6 0 6 0</Thickness>
    <Thickness x:Key="ResultMargin">0 0 0 6</Thickness>

    <Style x:Key="WindowRadius" TargetType="{x:Type Border}">
        <Setter Property="CornerRadius" Value="0" />
    </Style>
    <Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="Background" Value="{{ background }}" />
        <Setter Property="BorderBrush" Value="{{ foreground }}" />
        <Setter Property="BorderThickness" Value="2" />
        <Setter Property="CornerRadius" Value="0" />
    </Style>
    <Style x:Key="WindowStyle" BasedOn="{StaticResource BaseWindowStyle}" TargetType="{x:Type Window}" />

    <Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
        <Setter Property="CaretBrush" Value="{{ accent }}" />
        <Setter Property="SelectionBrush" Value="{{ selection }}" />
    </Style>
    <Style x:Key="QuerySuggestionBoxStyle" BasedOn="{StaticResource BaseQuerySuggestionBoxStyle}" TargetType="{x:Type TextBox}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="PendingLineStyle" BasedOn="{StaticResource BasePendingLineStyle}" TargetType="{x:Type Line}">
        <Setter Property="Stroke" Value="{{ accent }}" />
    </Style>
    <Style x:Key="SeparatorStyle" BasedOn="{StaticResource BaseSeparatorStyle}" TargetType="{x:Type Rectangle}">
        <Setter Property="Fill" Value="{{ muted }}" />
        <Setter Property="Height" Value="1" />
        <Setter Property="Margin" Value="0 0 0 6" />
    </Style>
    <Style x:Key="SearchIconStyle" BasedOn="{StaticResource BaseSearchIconStyle}" TargetType="{x:Type Path}">
        <Setter Property="Fill" Value="{{ dark_foreground }}" />
    </Style>

    <Style x:Key="ItemGlyph" BasedOn="{StaticResource BaseGlyphStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
    </Style>
    <Style x:Key="ItemGlyphSelectedStyle" BasedOn="{StaticResource BaseGlyphSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ accent }}" />
    </Style>
    <Style x:Key="ItemTitleStyle" BasedOn="{StaticResource BaseItemTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
    </Style>
    <Style x:Key="ItemSubTitleStyle" BasedOn="{StaticResource BaseItemSubTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="ItemNumberStyle" BasedOn="{StaticResource BaseItemNumberStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="ItemTitleSelectedStyle" BasedOn="{StaticResource BaseItemTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ accent }}" />
        <Setter Property="Cursor" Value="Arrow" />
    </Style>
    <Style x:Key="ItemSubTitleSelectedStyle" BasedOn="{StaticResource BaseItemSubTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
        <Setter Property="Cursor" Value="Arrow" />
    </Style>
    <SolidColorBrush x:Key="ItemSelectedBackgroundColor">{{ selected_row }}</SolidColorBrush>
    <Style x:Key="ItemImageSelectedStyle" BasedOn="{StaticResource BaseItemImageSelectedStyle}" TargetType="{x:Type Image}">
        <Setter Property="Cursor" Value="Arrow" />
    </Style>
    <Style x:Key="ItemHotkeyStyle" BasedOn="{StaticResource BaseItemHotkeyStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="ItemHotkeySelectedStyle" BasedOn="{StaticResource BaseItemHotkeySelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
    </Style>
    <Style x:Key="HighlightStyle">
        <Setter Property="Inline.FontWeight" Value="Bold" />
        <Setter Property="Inline.Foreground" Value="{{ accent }}" />
    </Style>

    <Style x:Key="ThumbStyle" BasedOn="{StaticResource BaseThumbStyle}" TargetType="{x:Type Thumb}">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Thumb}">
                    <Border Background="{{ muted }}" BorderThickness="0" CornerRadius="0" DockPanel.Dock="Right" />
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
    <Style x:Key="ScrollBarStyle" BasedOn="{StaticResource BaseScrollBarStyle}" TargetType="{x:Type ScrollBar}">
        <Setter Property="Width" Value="3" />
    </Style>

    <Style x:Key="ClockBox" BasedOn="{StaticResource BaseClockBox}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="DateBox" BasedOn="{StaticResource BaseDateBox}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="PreviewBorderStyle" BasedOn="{StaticResource BasePreviewBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="BorderBrush" Value="{{ muted }}" />
    </Style>
    <Style x:Key="PreviewItemTitleStyle" BasedOn="{StaticResource BasePreviewItemTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
    </Style>
    <Style x:Key="PreviewItemSubTitleStyle" BasedOn="{StaticResource BasePreviewItemSubTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ dark_foreground }}" />
    </Style>
    <Style x:Key="PreviewGlyph" BasedOn="{StaticResource BasePreviewGlyph}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{ foreground }}" />
    </Style>
</ResourceDictionary>
