# GlazeWM config - Omarchy (Hyprland) style. GENERATED by `winarchy apply` from
# templates/glazewm.yaml.tpl: edits here are replaced on the next apply/update.
# To customize: copy this template to %USERPROFILE%\.winarchy\glazewm.yaml.tpl (used instead)
# and run `winarchy apply`, or set "glazewmManaged": false in config.json to manage it yourself.
# Keybinds mirror Omarchy v4 default/hypr/bindings/tiling.lua; extras live in winarchy.ahk.
general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []

  # Hyprland follow_mouse = 1
  focus_follows_cursor: true

  # Hyprland default: no workspace back-and-forth.
  toggle_workspace_on_refocus: false

  # Hyprland warps the cursor to the focused window.
  cursor_jump:
    enabled: true
    trigger: 'window_focus'

  hide_method: 'cloak'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  # Hyprland gaps_in = 5 (per side) -> 10 between windows; gaps_out = 10.
  # The top gap also holds the bar (bar height + gap; the toggles rewrite these lines).
  inner_gap: '{{ gap }}px' # gaps
  outer_gap:
    top: '{{ gap_top }}px' # gaps:top
    right: '{{ gap }}px' # gaps
    bottom: '{{ gap }}px' # gaps
    left: '{{ gap }}px' # gaps
window_effects:
  focused_window:
    border:
      enabled: true
      color: '{{ focused_border }}' # theme:focused-border
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
      opacity: '98%'
  other_windows:
    border:
      enabled: true
      color: '#595959'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
      opacity: '96%'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false

{{ animations }}

# Workspaces are split across monitors (left to right) by winarchy apply.
workspaces:
{{ workspaces }}
  # Stand-in for Hyprland's special:scratchpad (opens on the focused monitor).
  - name: 'scratch'
    display_name: 'S'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_process: { equals: 'Flow.Launcher' }
      # winarchy screensaver windows (one per monitor).
      - window_title: { equals: 'Omarchy Screensaver' }
        window_process: { equals: 'WindowsTerminal' }
      # Windows system prompts (permission dialogs + their screen dim).
      - window_process: { equals: 'PickerHost' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_title: { equals: 'Command Palette' }
        window_class: { equals: 'WinUIDesktopWin32WindowClass' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

  # Small utility windows float centered (Omarchy floats calculator, btop, dialogs...).
  - commands: ['set-floating --centered']
    match:
      - window_process: { equals: 'CalculatorApp' }
      - window_process: { equals: 'Taskmgr' }
      - window_title: { equals: 'Omarchy About' }
        window_process: { equals: 'WindowsTerminal' }

binding_modes: []

keybindings:
  # --- Window state -------------------------------------------------------
  - commands: ['close']
    bindings: ['lwin+w', 'lwin+q']
  # SUPER+J (togglesplit) is handled in winarchy.ahk: it flips the existing
  # layout, which a plain binding here can't target.
  - commands: ['toggle-floating --centered']
    bindings: ['lwin+t']
  - commands: ['toggle-fullscreen --maximized=false']
    bindings: ['lwin+f']
  - commands: ['toggle-fullscreen --maximized']
    bindings: ['lwin+alt+f']
  - commands: ['toggle-floating --centered --shown-on-top']
    bindings: ['lwin+o']

  # --- Focus / swap -------------------------------------------------------
  - commands: ['focus --direction left']
    bindings: ['lwin+left']
  - commands: ['focus --direction right']
    bindings: ['lwin+right']
  - commands: ['focus --direction up']
    bindings: ['lwin+up']
  - commands: ['focus --direction down']
    bindings: ['lwin+down']
  - commands: ['move --direction left']
    bindings: ['lwin+shift+left']
  - commands: ['move --direction right']
    bindings: ['lwin+shift+right']
  - commands: ['move --direction up']
    bindings: ['lwin+shift+up']
  - commands: ['move --direction down']
    bindings: ['lwin+shift+down']
  - commands: ['move-workspace --direction left']
    bindings: ['lwin+shift+alt+left']
  - commands: ['move-workspace --direction right']
    bindings: ['lwin+shift+alt+right']
  - commands: ['move-workspace --direction up']
    bindings: ['lwin+shift+alt+up']
  - commands: ['move-workspace --direction down']
    bindings: ['lwin+shift+alt+down']

  # --- Workspace cycling --------------------------------------------------
  - commands: ['focus --next-active-workspace']
    bindings: ['lwin+tab']
  - commands: ['focus --prev-active-workspace']
    bindings: ['lwin+shift+tab']
  - commands: ['focus --recent-workspace']
    bindings: ['lwin+ctrl+tab']

  # --- Scratchpad (approximation) -----------------------------------------
  - commands: ['focus --workspace scratch']
    bindings: ['lwin+s', 'lwin+oem_tilde']
  - commands: ['move --workspace scratch']
    bindings: ['lwin+alt+s', 'lwin+shift+oem_tilde']

  # --- Resize (Omarchy: 100px, ALT 25px, CTRL 300px; SHIFT = height) -------
  - commands: ['resize --width -100px']
    bindings: ['lwin+oem_minus']
  - commands: ['resize --width +100px']
    bindings: ['lwin+oem_plus']
  - commands: ['resize --height -100px']
    bindings: ['lwin+shift+oem_minus']
  - commands: ['resize --height +100px']
    bindings: ['lwin+shift+oem_plus']
  - commands: ['resize --width -25px']
    bindings: ['lwin+alt+oem_minus']
  - commands: ['resize --width +25px']
    bindings: ['lwin+alt+oem_plus']
  - commands: ['resize --height -25px']
    bindings: ['lwin+shift+alt+oem_minus']
  - commands: ['resize --height +25px']
    bindings: ['lwin+shift+alt+oem_plus']
  - commands: ['resize --width -300px']
    bindings: ['lwin+ctrl+oem_minus']
  - commands: ['resize --width +300px']
    bindings: ['lwin+ctrl+oem_plus']
  - commands: ['resize --height -300px']
    bindings: ['lwin+shift+ctrl+oem_minus']
  - commands: ['resize --height +300px']
    bindings: ['lwin+shift+ctrl+oem_plus']

  # --- WM control (Windows extras) ----------------------------------------
  - commands: ['wm-reload-config']
    bindings: ['lwin+shift+alt+r']
  - commands: ['wm-toggle-pause']
    bindings: ['lwin+shift+alt+p']

  # --- Workspaces: SUPER+N go, SUPER+SHIFT+N move+follow, +ALT silent ------
  - commands: ['focus --workspace 1']
    bindings: ['lwin+1']
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lwin+shift+1']
  - commands: ['move --workspace 1']
    bindings: ['lwin+shift+alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['lwin+2']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lwin+shift+2']
  - commands: ['move --workspace 2']
    bindings: ['lwin+shift+alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['lwin+3']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lwin+shift+3']
  - commands: ['move --workspace 3']
    bindings: ['lwin+shift+alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['lwin+4']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['lwin+shift+4']
  - commands: ['move --workspace 4']
    bindings: ['lwin+shift+alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['lwin+5']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['lwin+shift+5']
  - commands: ['move --workspace 5']
    bindings: ['lwin+shift+alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['lwin+6']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lwin+shift+6']
  - commands: ['move --workspace 6']
    bindings: ['lwin+shift+alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['lwin+7']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['lwin+shift+7']
  - commands: ['move --workspace 7']
    bindings: ['lwin+shift+alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['lwin+8']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['lwin+shift+8']
  - commands: ['move --workspace 8']
    bindings: ['lwin+shift+alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['lwin+9']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['lwin+shift+9']
  - commands: ['move --workspace 9']
    bindings: ['lwin+shift+alt+9']
  - commands: ['focus --workspace 10']
    bindings: ['lwin+0']
  - commands: ['move --workspace 10', 'focus --workspace 10']
    bindings: ['lwin+shift+0']
  - commands: ['move --workspace 10']
    bindings: ['lwin+shift+alt+0']
